package ru.sad.base.navigation

enum class NavigationKey {
    // Fragments
    LOGIN_SCREEN,
    SPLASH_SCREEN,
    MAIN_SCREEN,
    PROFILE_SCREEN,
    PHOTO_STICKER_SCREEN,
    SUBSCRIPTION_SCREEN,
    CAMERA_SCREEN,
    CREATE_QUIZ_SCREEN,
    CREATE_QUIZ_FINAL_SCREEN,
    QUIZ_SCREEN,
    TOP_QUIZ_SCREEN,
    QUIZ_RESULT_SCREEN,
    ONBOARDING_SCREEN,


    // BOTTOM
    FRIENDS_BOTTOM_SHEET,

    // Other
    EXIT,
    EMPTY
}